In [1]:
import pandas as pd
import numpy as np
import random as rnd

import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
pd.set_option('Display.max_columns',500)
df=pd.read_excel('/content/Mtrain.xlsx')
df.head()
df.columns #prediction column "Transported is there"
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2343 entries, 0 to 2342
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Match_light_type        2310 non-null   object 
 1   Match_format            2273 non-null   object 
 2   Bowlers_in_team         2279 non-null   float64
 3   All_rounder_in_team     2305 non-null   float64
 4   First_selection         2303 non-null   object 
 5   Opponent                2307 non-null   object 
 6   Season                  2281 non-null   object 
 7   Offshore                2283 non-null   object 
 8   Max_wicket_taken_1over  2343 non-null   int64  
 9   Min_run_given_1over     2343 non-null   int64  
 10  Players_scored_zero     2343 non-null   int64  
 11  player_highest_wicket   2343 non-null   int64  
 12  Min_run_scored_1over    2323 non-null   float64
 13  extra_bowls_opponent    2343 non-null   int64  
 14  Extra_bowls_bowled      2343 non-null   

In [3]:
pd.set_option('Display.max_columns',500)
dt=pd.read_excel('/content/MTest.xlsx')
dt.head()
dt.columns #prediction column "Transported is there"
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 587 entries, 0 to 586
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Match_light_type        568 non-null    object 
 1   Match_format            587 non-null    object 
 2   Bowlers_in_team         569 non-null    float64
 3   All_rounder_in_team     585 non-null    float64
 4   First_selection         568 non-null    object 
 5   Opponent                587 non-null    object 
 6   Season                  587 non-null    object 
 7   Offshore                583 non-null    object 
 8   Max_wicket_taken_1over  587 non-null    int64  
 9   Min_run_given_1over     587 non-null    int64  
 10  Players_scored_zero     587 non-null    int64  
 11  player_highest_wicket   587 non-null    int64  
 12  Min_run_scored_1over    580 non-null    float64
 13  extra_bowls_opponent    587 non-null    int64  
 14  Extra_bowls_bowled      587 non-null    in

In [4]:
df.drop(['Max_run_scored_1over','First_selection'],axis=1,inplace=True)
dt.drop(['Max_run_scored_1over','First_selection'],axis=1,inplace=True)

In [5]:
dt.select_dtypes(include='object')
dt=pd.get_dummies(dt,drop_first=True)
dt.head()
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 587 entries, 0 to 586
Data columns (total 27 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Bowlers_in_team                 569 non-null    float64
 1   All_rounder_in_team             585 non-null    float64
 2   Max_wicket_taken_1over          587 non-null    int64  
 3   Min_run_given_1over             587 non-null    int64  
 4   Players_scored_zero             587 non-null    int64  
 5   player_highest_wicket           587 non-null    int64  
 6   Min_run_scored_1over            580 non-null    float64
 7   extra_bowls_opponent            587 non-null    int64  
 8   Extra_bowls_bowled              587 non-null    int64  
 9   Avg_team_Age                    572 non-null    float64
 10  Max_run_given_1over             581 non-null    float64
 11  Match_light_type_Day and Night  587 non-null    uint8  
 12  Match_light_type_Night          587 

In [6]:
df.select_dtypes(include='object')
df=pd.get_dummies(df,drop_first=True)
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2343 entries, 0 to 2342
Data columns (total 28 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Bowlers_in_team                 2279 non-null   float64
 1   All_rounder_in_team             2305 non-null   float64
 2   Max_wicket_taken_1over          2343 non-null   int64  
 3   Min_run_given_1over             2343 non-null   int64  
 4   Players_scored_zero             2343 non-null   int64  
 5   player_highest_wicket           2343 non-null   int64  
 6   Min_run_scored_1over            2323 non-null   float64
 7   extra_bowls_opponent            2343 non-null   int64  
 8   Extra_bowls_bowled              2343 non-null   int64  
 9   Avg_team_Age                    2261 non-null   float64
 10  Max_run_given_1over             2315 non-null   float64
 11  Result                          2343 non-null   int64  
 12  Match_light_type_Day and Night  23

In [9]:
df.isnull().sum()


Bowlers_in_team                   64
All_rounder_in_team               38
Max_wicket_taken_1over             0
Min_run_given_1over                0
Players_scored_zero                0
player_highest_wicket              0
Min_run_scored_1over              20
extra_bowls_opponent               0
Extra_bowls_bowled                 0
Avg_team_Age                      82
Max_run_given_1over               28
Result                             0
Match_light_type_Day and Night     0
Match_light_type_Night             0
Match_format_ODI                   0
Match_format_T20                   0
Match_format_Test                  0
Opponent_Bangladesh                0
Opponent_England                   0
Opponent_Kenya                     0
Opponent_Pakistan                  0
Opponent_South Africa              0
Opponent_Srilanka                  0
Opponent_West Indies               0
Opponent_Zimbabwe                  0
Season_Rainy                       0
Season_Summer                      0
O

In [8]:
dt.isnull().sum()

Bowlers_in_team                   18
All_rounder_in_team                2
Max_wicket_taken_1over             0
Min_run_given_1over                0
Players_scored_zero                0
player_highest_wicket              0
Min_run_scored_1over               7
extra_bowls_opponent               0
Extra_bowls_bowled                 0
Avg_team_Age                      15
Max_run_given_1over                6
Match_light_type_Day and Night     0
Match_light_type_Night             0
Match_format_ODI                   0
Match_format_T20                   0
Match_format_Test                  0
Opponent_Bangladesh                0
Opponent_England                   0
Opponent_Kenya                     0
Opponent_Pakistan                  0
Opponent_South Africa              0
Opponent_Srilanka                  0
Opponent_West Indies               0
Opponent_Zimbabwe                  0
Season_Summer                      0
Season_Winter                      0
Offshore_Yes                       0
d

In [27]:
dt.isnull().sum()

Bowlers_in_team                   0
All_rounder_in_team               0
Max_wicket_taken_1over            0
Min_run_given_1over               0
Players_scored_zero               0
player_highest_wicket             0
Min_run_scored_1over              0
extra_bowls_opponent              0
Extra_bowls_bowled                0
Avg_team_Age                      0
Max_run_given_1over               0
Match_light_type_Day and Night    0
Match_light_type_Night            0
Match_format_ODI                  0
Match_format_T20                  0
Match_format_Test                 0
Opponent_Bangladesh               0
Opponent_England                  0
Opponent_Kenya                    0
Opponent_Pakistan                 0
Opponent_South Africa             0
Opponent_Srilanka                 0
Opponent_West Indies              0
Opponent_Zimbabwe                 0
Season_Summer                     0
Season_Winter                     0
Offshore_Yes                      0
dtype: int64

In [28]:
df.isnull().sum()

Bowlers_in_team                   0
All_rounder_in_team               0
Max_wicket_taken_1over            0
Min_run_given_1over               0
Players_scored_zero               0
player_highest_wicket             0
Min_run_scored_1over              0
extra_bowls_opponent              0
Extra_bowls_bowled                0
Avg_team_Age                      0
Max_run_given_1over               0
Result                            0
Match_light_type_Day and Night    0
Match_light_type_Night            0
Match_format_ODI                  0
Match_format_T20                  0
Match_format_Test                 0
Opponent_Bangladesh               0
Opponent_England                  0
Opponent_Kenya                    0
Opponent_Pakistan                 0
Opponent_South Africa             0
Opponent_Srilanka                 0
Opponent_West Indies              0
Opponent_Zimbabwe                 0
Season_Rainy                      0
Season_Summer                     0
Offshore_Yes                

In [25]:
df['Avg_team_Age'].fillna(df['Avg_team_Age'].mean(),inplace=True)
dt['Avg_team_Age'].fillna(dt['Avg_team_Age'].mean(),inplace=True)

df['Bowlers_in_team'].fillna(df['Bowlers_in_team'].median(),inplace=True)
dt['Bowlers_in_team'].fillna(dt['Bowlers_in_team'].median(),inplace=True)

df['All_rounder_in_team'].fillna(df['All_rounder_in_team'].median(),inplace=True)
dt['All_rounder_in_team'].fillna(dt['All_rounder_in_team'].median(),inplace=True)

df['Min_run_scored_1over'].fillna(df['Min_run_scored_1over'].median(),inplace=True)
dt['Min_run_scored_1over'].fillna(dt['Min_run_scored_1over'].median(),inplace=True)

df['Max_run_given_1over'].fillna(df['Max_run_given_1over'].median(),inplace=True)
dt['Max_run_given_1over'].fillna(dt['Max_run_given_1over'].median(),inplace=True)








In [26]:
df['Result'].value_counts()
df.shape

(2343, 28)

In [11]:
dt.shape

(587, 27)

In [29]:
X=df.drop(['Result'],axis=1)
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2343 entries, 0 to 2342
Data columns (total 27 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Bowlers_in_team                 2343 non-null   float64
 1   All_rounder_in_team             2343 non-null   float64
 2   Max_wicket_taken_1over          2343 non-null   int64  
 3   Min_run_given_1over             2343 non-null   int64  
 4   Players_scored_zero             2343 non-null   int64  
 5   player_highest_wicket           2343 non-null   int64  
 6   Min_run_scored_1over            2343 non-null   float64
 7   extra_bowls_opponent            2343 non-null   int64  
 8   Extra_bowls_bowled              2343 non-null   int64  
 9   Avg_team_Age                    2343 non-null   float64
 10  Max_run_given_1over             2343 non-null   float64
 11  Match_light_type_Day and Night  2343 non-null   uint8  
 12  Match_light_type_Night          23

In [30]:
y=df['Result']
y


0       0
1       1
2       0
3       1
4       0
       ..
2338    1
2339    1
2340    1
2341    1
2342    1
Name: Result, Length: 2343, dtype: int64

In [31]:
#Splitting the dataset (we will name as train and validation dataset)
from sklearn.model_selection import train_test_split
X_train,X_valid,y_train,y_valid=train_test_split(X,y,test_size=0.2,random_state=4)

In [32]:
#Standardization of dataset
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_train


array([[-0.85975015,  1.16755795,  1.18945982, ..., -0.87821782,
         1.47157757, -0.62301537],
       [ 1.10389614, -1.60206686, -1.60033705, ...,  1.13866967,
        -0.67954284, -0.62301537],
       [ 1.10389614,  1.16755795, -1.60033705, ..., -0.87821782,
         1.47157757,  1.60509684],
       ...,
       [ 0.122073  , -0.67885859, -0.67040476, ...,  1.13866967,
        -0.67954284, -0.62301537],
       [ 0.122073  ,  1.16755795,  0.25952753, ...,  1.13866967,
        -0.67954284, -0.62301537],
       [ 0.122073  ,  0.24434968, -0.67040476, ...,  1.13866967,
        -0.67954284, -0.62301537]])

In [33]:
X_valid=sc.transform(X_valid)
X_valid

array([[ 0.122073  ,  0.24434968, -1.60033705, ..., -0.87821782,
         1.47157757, -0.62301537],
       [-0.85975015, -1.60206686,  1.18945982, ...,  1.13866967,
        -0.67954284, -0.62301537],
       [ 0.122073  ,  0.24434968, -0.67040476, ...,  1.13866967,
        -0.67954284, -0.62301537],
       ...,
       [-1.84157329, -1.60206686,  0.25952753, ..., -0.87821782,
        -0.67954284, -0.62301537],
       [ 0.122073  ,  1.16755795,  1.18945982, ..., -0.87821782,
        -0.67954284, -0.62301537],
       [-1.84157329, -0.67885859,  1.18945982, ..., -0.87821782,
         1.47157757, -0.62301537]])

In [34]:
df_test_scaled=sc.fit_transform(dt)
df_test_scaled

array([[-0.10991865, -0.66394024,  1.23494479, ...,  1.57269602,
        -0.53598573,  1.63363093],
       [ 0.94782314,  0.2466507 ,  0.31383603, ..., -0.63585078,
         1.86572132,  1.63363093],
       [ 0.94782314, -1.57453117,  1.23494479, ..., -0.63585078,
         1.86572132, -0.61213337],
       ...,
       [ 0.94782314,  0.2466507 ,  1.23494479, ..., -0.63585078,
        -0.53598573,  1.63363093],
       [ 0.94782314,  0.2466507 , -0.60727273, ..., -0.63585078,
        -0.53598573, -0.61213337],
       [ 0.94782314,  0.2466507 ,  1.23494479, ..., -0.63585078,
        -0.53598573, -0.61213337]])

In [35]:
print(X_train.shape)
print(X_valid.shape)
print(df_test_scaled.shape)


(1874, 27)
(469, 27)
(587, 27)


In [36]:
#random forest
from sklearn.ensemble import RandomForestClassifier 
rdf = RandomForestClassifier(n_estimators = 10, criterion= 'gini')

In [43]:
rdf.fit(X_train,y_train)
y_pred_rdf=rdf.predict(X_valid)

In [44]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report,roc_auc_score
confusion_matrix(y_valid, y_pred_rdf)
accuracy_score(y_valid,y_pred_rdf)
classification_report(y_valid, y_pred_rdf)
roc_auc_score(y_valid,y_pred_rdf)

0.8423645320197044

In [45]:
y_test_pred=rdf.predict(df_test_scaled)
y_test_pred


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [47]:
#Generating csv for submission
#since we had removed columns we will take the data once again
df_test_data=pd.read_excel('/content/MTest.xlsx')
df_test_data.columns


Index(['Match_light_type', 'Match_format', 'Bowlers_in_team',
       'All_rounder_in_team', 'First_selection', 'Opponent', 'Season',
       'Offshore', 'Max_wicket_taken_1over', 'Min_run_given_1over',
       'Players_scored_zero', 'player_highest_wicket', 'Min_run_scored_1over',
       'extra_bowls_opponent', 'Extra_bowls_bowled', 'Avg_team_Age',
       'Max_run_given_1over', 'Max_run_scored_1over'],
      dtype='object')

In [51]:
sub=pd.DataFrame({
    'Result':y_test_pred})


In [52]:
sub.to_csv('submission.csv',index=False)